### ISSUE TITLE
Protobuf / network lib issue : multi-dimensional array flattened

### ISSUE THREAD

**Issue by lbarman** [dedis/protobuf#19]
Hi,

Using the SDA / network lib / protobuf lib, if I try to pass a 2-by-2 array in a registered message with a field [][]abstract.Point, with content such as 

```
keys := make([]abstract.Keys, 2)
keys[0] = make([]abstract.Point, 2)
keys[1] = make([]abstract.Point, 2)
keys[0][0] = a
keys[0][1] = b
keys[1][0] = c
keys[1][1] = d
```

I receive a 4-1 _multi-dimensional_ array, such as 

```
keysReceived[0][0] = a
keysReceived[1][0] = b
keysReceived[2][0] = c
keysReceived[3][0] = d
```

whereas the same structure was expected. The bug is visible in branch prifi, lib/prifi/trustee.go:301, where I had to write code to reshape the array

**Comment by ineiti** [comment]
Thanks Ludovic for the bug-report. Would you have the time to write a failing test like I did in #15 ? That helps a lot to check where the bug comes from and how to make sure it's fixed.

**Comment by ineiti** [comment]
Probably also works with Ismail's change.

**Comment by Liamsi** [comment]
> Probably also works with Ismail's change.

I suspect the issue also isn't fixed. I only changed how map-values are handled while decoding their values. I can write a test for what @lbarman described, but I guess @nikkolasg would be faster resolving the issue as he wrote the array/slice de-/encode code.

**Comment by Liamsi** [comment]
I tried to write a test: 
```
testSuite := edwards.NewAES128SHA256Ed25519(false)
	a, b, c, d := testSuite.Point(), testSuite.Point(),testSuite.Point(),testSuite.Point()
	keys := make([][]abstract.Point, 2)
	keys[0] = make([]abstract.Point, 2)
	keys[1] = make([]abstract.Point, 2)
	keys[0][0] = a
	keys[0][1] = b
	keys[1][0] = c
	keys[1][1] = d

	_, err := Encode(&keys)
	assert.NoError(t, err)
```
and it actually even fails while encoding: 
```
--- FAIL: TestMultidimensionalSlices (0.00s)
        Error Trace:    protobuf_test.go:281
        Error:          Received unexpected error "reflect: NumField of non-struct type"
                
FAIL
exit status 1
FAIL    github.com/dedis/protobuf       0.014s
```

**Comment by ineiti** [comment]
Can you make a PR with that test-case failing?

**Comment by Liamsi** [comment]
Sure, but don't merge it, as it depends on dedis/crypto as I wanted to reproduce @lbarman's error

**Comment by Liamsi** [comment]
Added a commit (see above)

**Comment by Liamsi** [comment]
Reproduce with `go test -run TestMultidimensionalSlices`

**Comment by nikkolasg** [comment]
It is in fact no possible to encode double dimensional arrays with protobuf (see [link](https://stackoverflow.com/questions/20968626/how-can-i-represent-a-2-dimensional-array-in-protocol-buffers)).
The best bet for now is to create a wrapper struct and have 
```
type myStruct struct {
    Elem  int
}
myArr := make([]myStruct,0)
```

**Comment by nikkolasg** [comment]
After discussion, it seems also a good idea to return an error in such cases, instead of silently encode something wrong.
