### ISSUE TITLE
Cannot encode map[[16]byte]string

### ISSUE THREAD

**Issue by kc1212** [dedis/protobuf#52]
I wrote the following test in `encoding_test.go`:

```
type ArrayMapT struct {
	Dummy string
	Map   map[[16]byte]string
}

func TestArrayMap(t *testing.T) {
	m := make(map[[16]byte]string)
	m[[16]byte{0}] = "zero"
	m[[16]byte{1}] = "one"
	t0 := ArrayMapT{
		Dummy: "test",
		Map:   m,
	}
	buf, err := Encode(&t0)
	assert.Nil(t, err)

	var t1 ArrayMapT
	err = Decode(buf, &t1)
	assert.Nil(t, err)
}
```

But it fails at the `Encode` part with error "reflect.Value.Slice: slice of unaddressable array (field Map)".  Is encoding go maps that uses arrays as its key supported?

**Comment by ineiti** [comment]
I was not even aware that we could use arrays in map-indexes ;) One thing I saw also is that `map[string]otherStruct` doesn't work, but `map[string]*otherStruct` _does_ work.

**Comment by jeffallen** [comment]
This works as of commit 62ad0cc155.
